### ISSUE TITLE
Not authorized to send Apple events to System Events

### ISSUE THREAD

**Issue by epk** [katernet/darkmode#3]
On the latest beta

07/04/18 00:45:11 102:106: execution error: Not authorized to send Apple events to System Events. (-1743)
07/04/18 00:45:11 /Users/paranoidaditya/Documents/darkmode.sh: line 36: [[: File Doesn't Exist, Will Create: /Users/paranoidaditya/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist: syntax error: invalid arithmetic operator (error token is "'t Exist, Will Create: /Users/paranoidaditya/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist")
07/04/18 00:45:11 /Users/paranoidaditya/Documents/darkmode.sh: line 36: [[: File Doesn't Exist, Will Create: /Users/paranoidaditya/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist: syntax error: invalid arithmetic operator (error token is "'t Exist, Will Create: /Users/paranoidaditya/Library/LaunchAgents/io.github.katernet.darkmode.sunset.plist")
04/07/18 00:45:14 darkmode: Solar query stored - Sunrise: 05:26 Sunset: 21:40
07/04/18 00:45:14 102:107: execution error: Not authorized to send Apple events to System Events. (-1743)
07/04/18 00:46:17 102:107: execution error: Not authorized to send Apple events to System Events. (-1743)
07/04/18 00:46:20 102:107: execution error: Not authorized to send Apple events to System Events. (-1743)
07/04/18 00:46:25 102:107: execution error: Not authorized to send Apple events to System Events. (-1743)
07/04/18 00:46:32 102:107: execution error: Not authorized to send Apple events to System Events. (-1743)
07/04/18 00:46:38 102:107: execution error: Not authorized to send Apple events to System Events. (-1743)

**Comment by katernet** [comment]
It seems your script is now in Documents, which would break if it's in a path different from first run - First note: https://github.com/katernet/darkmode/tree/bb2f6af7e4b1c1efb701c92c7a23103bfd25f6a3

Try version v1.6 which I just released, it explicity sets the script path in ~/Library/Application Support/darkmode/

The errors mentioning line 36 have also fixed in this release - Stopped uninstall function from querying the launch agents, which wouldn't exist after uninstall.

**Comment by epk** [comment]
Still have the Not authorized to send to Apple events to System Events error

`07/06/18 21:39:40 102:106: execution error: Not authorized to send Apple events to System Events. (-1743)
06/07/18 21:39:44 darkmode: Solar query stored - Sunrise: 05:28 Sunset: 21:39
07/06/18 21:39:45 102:107: execution error: Not authorized to send Apple events to System Events. (-1743)
`

**Comment by katernet** [comment]
Thanks I'll look into it. 

By on the latest beta do you mean you're on Mojave dev beta 3?

**Comment by epk** [comment]
Yes! Dev Beta 3

**Comment by katernet** [comment]
Updated to beta 3 and the unauthorized execution error is returned in Terminal when simply running the AppleScript command to enable dark mode.

When executing the AppleScript in a shell script within TextMate, a dialogue pops up asking to allow TextMate to access System Events. This adds TextMate to Automation in Security preferences to allow access to System Events and then it works. Running the AppleScript within Script Editor works fine.

I found this article on the new security feature https://www.felix-schwarz.org/blog/2018/06/apple-event-sandboxing-in-macos-mojave

I am not even sure how to allow my script access to System Events within this security feature.

Any ideas?

**Comment by katernet** [comment]
When setting a future time to test triggering Mojave Dark Mode, a dialogue opened asking to allow "darkmode.sh" to control System Events. I turned off macOS Dark Mode and switched wallpapers and darkmode.sh now works. 

I cannot see it displayed in Security Automation preferences and I am not sure how else to get the dialogue to display. Possibly it will display when the launch agents trigger the script without manually changing the time.

I can see the path to darkmode.sh is now in the database ~/Library/Application Support/com.apple.TCC/TCC.db to allow access to System Events. I guess you could write to the access table in the database, but this is a bit too hacky.

So it seems the way to allow darkmode.sh access to System Events is to set a future time on the next day so the launch agent triggers and then choose to allow control of System Events in the security dialogue. Or just use dev 3/wait for next public beta/release 😝

**Comment by ApolloZhu** [comment]
@katernet if you don't mind, could you please point me to the info about dynamic dark mode?

**Comment by katernet** [comment]
@ApolloZhu Please be more specific and this issue is to do with the AppleScript error in the title. Please open a new issue.

**Comment by katernet** [comment]
Good news everyone! darkmode is now working in Mojave in the latest dev and public beta. After running the script a security window shows asking to allow access System Events and pressing OK will allow the script to run.

**Comment by skull4d** [comment]
Is there any way or command to add an application in System Prefrences > Privacy >Automation > terminal
running beta 8

**Comment by katernet** [comment]
I don't think so. In Mojave dev beta 5/public beta 4 and above, when the script runs press OK to the System Events dialogue and it will add it in there (need to wait for the next solar time for the job to run the script, if you run from Terminal it will add Terminal in there. Or you could run it manually by using `launchctl start io.github.katernet.darkmode.sunrise.plist` for example)

**Comment by Toxblh** [comment]
https://indiestack.com/2018/08/apple-events-usage-description/
if short 
In `Info.plist` need to add `Privacy - AppleEvents Sending Usage Description` or `NSAppleEventsUsageDescription` in raw keys/values and any description
